[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
derive_more = "0.99"
itertools = "0.10"
derive_builder = "0.11.1"
chrono = { version = "0.4" }